export const GET_MONTH_TURNS = 'GET_MONTH_TURNS';
export const SAVE_TURN = 'SAVE_TURN';

export const TOGGLE_SEE_HOUR_LIST = 'TOGGLE_SEE_HOUR_LIST';
export const TOGGLE_SEE_CLIENT_RESERVATION = 'TOGGLE_SEE_CLIENT_RESERVATION';
export const DAY_TO_SAVE = 'DAY_TO_SAVE';
export const FILL_DATA_HOUR_RESERVATION = 'FILL_DATA_HOUR_RESERVATION';
export const FILL_CLIENT_DATA = 'FILL_CLIENT_DATA';

export const DELETE_DAY_FROM_DAYWITHOWNTURNS = 'DELETE_DAY_FROM_DAYWITHOWNTURNS';

export const INITILIZE_DAYWITHOWNTURNS = 'INITILIZE_DAYWITHOWNTURNS';
export const INITIALIZE_MONTH_TURNS = 'INITIALIZE_MONTH_TURNS';

export const TOGGLE_CANCELED_TURN = 'TOGGLE_CANCELED_TURN';
export const DELETE_TURN_DB = 'DELETE_TURN_DB';

export const TOGGLE_RELOAD = 'TOGGLE_RELOAD';

export const TOGGLE_ERROR_SAVING_TURN = 'TOGGLE_ERROR_SAVING_TURN';
export const TOGGLE_ERROR_DELETING_TURN = 'TOGGLE_ERROR_DELETING_TURN';
export const STORE_DATA_MONTH_TO_SEEK = 'STORE_DATA_MONTH_TO_SEEK';

export const SEND_EMAIL = 'SEND_EMAIL';
export const SEND_DATA_LOGIN = 'SEND_DATA_LOGIN';
export const SEND_DATA_LOGIN_ADMIN = 'SEND_DATA_LOGIN_ADMIN';
export const CLEAR_LOGIN_ADMIN_ERROR = 'CLEAR_LOGIN_ADMIN_ERROR';
export const CLEAR_LOGIN_ADMIN_ALL = 'CLEAR_LOGIN_ADMIN_ALL';

export const SEND_DATA_LOGIN_DOCTOR = 'SEND_DATA_LOGIN_DOCTOR';
export const CLEAR_LOGIN_DOCTOR_ERROR = 'CLEAR_LOGIN_DOCTOR_ERROR';
export const CLEAR_LOGIN_DOCTOR_ALL = 'CLEAR_LOGIN_DOCTOR_ALL';

