export const GET_MONTH_TURNS = "GET_MONTH_TURNS";
export const SAVE_TURN = "SAVE_TURN";

export const TOGGLE_SEE_HOUR_LIST = "TOGGLE_SEE_HOUR_LIST";
export const TOGGLE_SEE_CLIENT_RESERVATION = "TOGGLE_SEE_CLIENT_RESERVATION";
export const DAY_TO_SAVE = "DAY_TO_SAVE";
export const FILL_DATA_HOUR_RESERVATION = "FILL_DATA_HOUR_RESERVATION";
export const FILL_CLIENT_DATA = "FILL_CLIENT_DATA";

export const DELETE_DAY_FROM_DAYWITHOWNTURNS =
  "DELETE_DAY_FROM_DAYWITHOWNTURNS";
export const DELETE_ALL_DAYS_FROM_DAYWITHOWNTURNS =
  "DELETE_ALL_DAYS_FROM_DAYWITHOWNTURNS";

export const INITILIZE_DAYWITHOWNTURNS = "INITILIZE_DAYWITHOWNTURNS";
export const INITIALIZE_MONTH_TURNS = "INITIALIZE_MONTH_TURNS";

export const TOGGLE_CANCELED_TURN = "TOGGLE_CANCELED_TURN";
export const CLEAR_CANCELED_TURN = "CLEAR_CANCELED_TURN";
export const SEND_TO_GLOBAL_STORE = "SEND_TO_GLOBAL_STORE";

export const DELETE_TURN_DB = "DELETE_TURN_DB";

export const TOGGLE_RELOAD = "TOGGLE_RELOAD";

export const TOGGLE_ERROR_SAVING_TURN = "TOGGLE_ERROR_SAVING_TURN";
export const TOGGLE_ERROR_DELETING_TURN = "TOGGLE_ERROR_DELETING_TURN";
export const TOGGLE_ERROR_DELETING_TURN_ALL = "TOGGLE_ERROR_DELETING_TURN_ALL";
export const TOGGLE_ERROR_DISABLING_TURN = "TOGGLE_ERROR_DISABLING_TURN";
export const TOGGLE_ERROR_ENABLING_TURN = "TOGGLE_ERROR_ENABLING_TURN";
export const TOGGLE_ERROR_SENDING_EMAIL = "TOGGLE_ERROR_SENDING_EMAIL";
export const STORE_DATA_MONTH_TO_SEEK = "STORE_DATA_MONTH_TO_SEEK";

export const SEND_EMAIL = "SEND_EMAIL";
export const SEND_DATA_LOGIN = "SEND_DATA_LOGIN";
export const SEND_DATA_LOGIN_ADMIN = "SEND_DATA_LOGIN_ADMIN";
export const CLEAR_LOGIN_ADMIN_ERROR = "CLEAR_LOGIN_ADMIN_ERROR";
export const CLEAR_LOGIN_ADMIN_ALL = "CLEAR_LOGIN_ADMIN_ALL";

export const SEND_DATA_LOGIN_DOCTOR = "SEND_DATA_LOGIN_DOCTOR";
export const CLEAR_LOGIN_DOCTOR_ERROR = "CLEAR_LOGIN_DOCTOR_ERROR";
export const CLEAR_LOGIN_DOCTOR_ALL = "CLEAR_LOGIN_DOCTOR_ALL";

export const RECOVER_DOCTORS_LIST = "RECOVER_DOCTORS_LIST";

export const ACTIVATE_DAY = "ACTIVATE_DAY";

export const DISABLE_TURN = "DISABLE_TURN";
export const DISABLING_TURN_DATA = "DISABLING_TURN_DATA";
export const ENABLE_TURN = "ENABLE_TURN;";

export const TOGGLE_IS_DOCTOR_DISABLE_TURN = "TOGGLE_IS_DOCTOR_DISABLE_TURN";

export const DELETE_AND_DISABLE_TURN = "DELETE_AND_DISABLE_TURN";
export const TOGGLE_WAITING_RESPONSE = "TOGGLE_WAITING_RESPONSE";
export const TOGGLE_DELETE_AND_DISABLE_ERROR =
  "TOGGLE_DELETE_AND_DISABLE_ERROR";
export const TOGGLE_DELETE_AND_DISABLE_ERROR_AND_CANCELEDGLOBALSTORE =
  "TOGGLE_DELETE_AND_DISABLE_ERROR_AND_CANCELEDGLOBALSTORE";

export const DISABLE_ALL_DAY = "DISABLE_ALL_DAY";
export const SET_DISABLE_ALL_DAY_STATUS = "SET_DISABLE_ALL_DAY_STATUS";
export const CLEAR_DISABLE_ALL_DAY_STATUS = "CLEAR_DISABLE_ALL_DAY_STATUS";
export const TOGGLE_DISABLE_ALL_DAY_EMAIL_ERROR_AND_CANCELEDGLOBALSTORE =
  "TOGGLE_DISABLE_ALL_DAY_EMAIL_ERROR_AND_CANCELEDGLOBALSTORE";

export const TOGGLE_ERROR_SAVING_TURN_AND_CANCELEDGLOBALSTORE =
  "TOGGLE_ERROR_SAVING_TURN_AND_CANCELEDGLOBALSTORE";
export const TOGGLE_ERROR_ACTIVATING_DAY = "TOGGLE_ERROR_ACTIVATING_DAY";

export const SET_CANCELEDGLOBALSTORE = "SET_CANCELEDGLOBALSTORE";

export const SET_PATIENT_DATA = "SET_PATIENT_DATA";

export const CHANGE_DOCTOR_PASSWORD = "CHANGE_DOCTOR_PASSWORD";
export const CLEAR_LOGIN_DOCTOR = "CLEAR_LOGIN_DOCTOR";

export const RECOVER_PASSWORD_DOCTOR = "RECOVER_PASSWORD_DOCTOR";

export const GET_DOCTOR_LIST = "GET_DOCTOR_LIST";
export const CLEAR_DOCTOR_LIST = "CLEAR_DOCTOR_LIST";
export const CHANGE_DOCTOR_STATUS = "CHANGE_DOCTOR_STATUS";
export const CHANGE_DOCTOR_ADMIN_STATUS = "CHANGE_DOCTOR_ADMIN_STATUS";

export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const DELETE_DOCTOR_FROM_DB = "DELETE_DOCTOR_FROM_DB";

export const TOGGLE_INSTRUCTIONS_BUTTON = "TOGGLE_INSTRUCTIONS_BUTTON";
